### ISSUE TITLE
Content suggestion: Please update status and usage instructions in description.

### ISSUE THREAD

**Issue by Koladweep** [sayan01/se2001-book#1]
Please add the following details to the description:
1) Status of completion.
2) Instructions/link to instruction on how to deploy and run locally.

Thanks. Keep up the good work. You rock!

**Comment by sayan01** [comment]
Thanks.

1. you can refer to the commit histories, or the pdf for it
2. to simply read the book you can just access the pdf file, to develop you can change the `.tex` files and call the `./compileAll` script. The required dependencies of latex and latex packages should be installed.

**Comment by Koladweep** [comment]
I see. main.pdf you mean. Sorry for having missed that.
> 2\. just access the pdf file
https://github.com/sayan01/se2001-book/blob/master/main.pdf

**Comment by sayan01** [comment]
Yes, this.
